CREATE OR ALTER VIEW V_GUIDE_TRADITIONAL_MARK(
    TRADITIONAL_MARKID,
    TRADITIONAL_MARK,
    CREDITS_MIN,
    MARKSTR,
    MARKSTR_ENG,
    MARKSTR_RUS,
    TRADITIONAL_MARK_RUS,
    MARKSTR_UKR,
    TRADITIONAL_MARK_UKR)
AS
select
  G.TRADITIONAL_MARKID,
  (case P.PARAMETERVALUE
  when 'RUS' then G.TRADITIONAL_MARK_RUS else G.TRADITIONAL_MARK end) as TRADITIONAL_MARK,
  G.CREDITS_MIN,
  (case P.PARAMETERVALUE
  when 'RUS' then G.MARKSTR_RUS else G.MARKSTR end) as MARKSTR,
  G.MARKSTR_ENG,
  G.MARKSTR_RUS,
  G.TRADITIONAL_MARK_RUS,
  G.MARKSTR as MARKSTR_UKR,
  G.TRADITIONAL_MARK as TRADITIONAL_MARK_UKR
from GUIDE_TRADITIONAL_MARK G
inner join PARAMETERS P
  on P.PARAMETERNAME = 'Country'
;